In [3]:
import pandas as pd
import numpy as np
# create art lang ratios

In [114]:
df = pd.read_csv('../table_revised_2.txt', sep="\t", header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,85,86,87,88,89,90,91,92,93,94
0,Siciliano,+,+,+,-,+,0,+,0,0,...,-,-,0,+,0,-,0,0,0,0
1,Calabrese_Northern,+,+,+,-,+,0,+,0,0,...,+,-,0,+,0,-,0,0,0,0
2,Italian,+,+,+,-,+,0,+,0,0,...,+,-,0,+,-,-,0,0,0,0
3,Spanish,+,+,+,-,+,0,+,0,0,...,-,-,0,+,-,+,0,0,0,0
4,French,+,+,+,-,+,0,+,0,0,...,-,+,-,0,0,0,0,0,0,-

In [115]:
df1 = pd.read_csv('../Artificial_Langs/split.txt', sep="\t", header=None)
df1.head()

  0  1  2  3  4  5  6  7  8  9   ... 62 63 64 65 66 67 68 69 70 71
0  +  +  +  +  +  +  +  +  +  +  ...  ,  +  +  ,  +  ,  +  ,  +  +
1  +  +  +  +  +  +  +  +  +  +  ...  ,  +  +  ,  +  ,  -  ,  +  +
2  +  +  +  +  +  +  +  +  +  +  ...  ,  +  +  ,  -  ,  +  ,  +  +
3  -  -  -  -  -  -  -  -  -  -  ...  ,  -  -  ,  0  ,  -  ,  -  -
4  +  +  +  +  +  +  +  +  +  +  ...  ,  +  +  ,  +  ,  +  ,  +  +

[5 rows x 72 columns]

In [116]:
df.shape, df1.shape

((58, 95), (94, 72))

In [117]:
df = df.iloc[:,1:].T
df = df.reset_index(drop=True)
df.shape

(94, 58)

In [121]:
print(df)

   0  1  2  3  4  5  6  7  8  9   ... 48 49 50 51 52 53 54 55 56 57
0   +  +  +  +  +  +  +  +  +  +  ...  +  +  +  +  +  +  +  +  +  +
1   +  +  +  +  +  +  +  +  +  +  ...  +  +  +  +  +  +  +  -  +  +
2   +  +  +  +  +  +  +  +  +  +  ...  +  +  +  +  +  +  -  +  +  +
3   -  -  -  -  -  -  -  -  -  -  ...  -  -  -  -  -  -  0  -  -  -
4   +  +  +  +  +  +  +  +  +  +  ...  +  +  +  +  +  +  +  +  +  +
.. .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
89  -  -  -  +  0  -  -  -  +  +  ...  +  +  +  -  0  0  -  0  0  0
90  0  0  0  0  0  0  0  0  +  +  ...  0  0  0  0  0  0  0  0  0  0
91  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
92  0  0  0  0  0  0  0  0  -  -  ...  0  0  0  0  0  0  0  0  0  0
93  0  0  0  0  -  0  0  0  +  +  ...  0  0  0  +  0  +  0  -  +  +

[94 rows x 58 columns]

In [119]:
df1

   0  1  2  3  4  5  6  7  8  9   ... 62 63 64 65 66 67 68 69 70 71
0   +  +  +  +  +  +  +  +  +  +  ...  ,  +  +  ,  +  ,  +  ,  +  +
1   +  +  +  +  +  +  +  +  +  +  ...  ,  +  +  ,  +  ,  -  ,  +  +
2   +  +  +  +  +  +  +  +  +  +  ...  ,  +  +  ,  -  ,  +  ,  +  +
3   -  -  -  -  -  -  -  -  -  -  ...  ,  -  -  ,  0  ,  -  ,  -  -
4   +  +  +  +  +  +  +  +  +  +  ...  ,  +  +  ,  +  ,  +  ,  +  +
.. .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
89  -  -  -  +  0  -  -  -  +  +  ...  ,  0  0  ,  -  ,  0  ,  0  0
90  0  0  0  0  0  0  0  0  +  +  ...  ,  0  0  ,  0  ,  0  ,  0  0
91  0  0  0  0  0  0  0  0  0  0  ...  ,  0  0  ,  0  ,  0  ,  0  0
92  0  0  0  0  0  0  0  0  -  -  ...  ,  0  0  ,  0  ,  0  ,  0  0
93  0  0  0  0  -  0  0  0  +  +  ...  ,  0  +  ,  0  ,  -  ,  +  +

[94 rows x 72 columns]

In [120]:
i = 0
for col in df1.columns:
    if df1[col].iloc[0] == ",":
        i += 1
    else:
        df1[col] = df[col - i]
df1

   0  1  2  3  4  5  6  7  8  9   ... 62 63 64 65 66 67 68 69 70 71
0   +  +  +  +  +  +  +  +  +  +  ...  ,  +  +  ,  +  ,  +  ,  +  +
1   +  +  +  +  +  +  +  +  +  +  ...  ,  +  +  ,  +  ,  -  ,  +  +
2   +  +  +  +  +  +  +  +  +  +  ...  ,  +  +  ,  -  ,  +  ,  +  +
3   -  -  -  -  -  -  -  -  -  -  ...  ,  -  -  ,  0  ,  -  ,  -  -
4   +  +  +  +  +  +  +  +  +  +  ...  ,  +  +  ,  +  ,  +  ,  +  +
.. .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
89  -  -  -  +  0  -  -  -  +  +  ...  ,  0  0  ,  -  ,  0  ,  0  0
90  0  0  0  0  0  0  0  0  +  +  ...  ,  0  0  ,  0  ,  0  ,  0  0
91  0  0  0  0  0  0  0  0  0  0  ...  ,  0  0  ,  0  ,  0  ,  0  0
92  0  0  0  0  0  0  0  0  -  -  ...  ,  0  0  ,  0  ,  0  ,  0  0
93  0  0  0  0  -  0  0  0  +  +  ...  ,  0  +  ,  0  ,  -  ,  +  +

[94 rows x 72 columns]

In [148]:
df1.to_csv("../Artificial_Langs/split_revision_2.txt",  sep='\t', index=False, header=False)

In [149]:
da = [0.933, 0.786, 0.929, 0.141, 0.857, 0.333, 1.0, 0.0, 0.5, 0.75, 0.996, 0.067, 0.411, 0.375, 0.649, 0.0, 0.243, 0.154, 0.595, 0.246, 0.409, 0.25, 0.333, 0.048, 0.222, 0.167, 1.0, 0.5, 0.083, 0.0, 0.564, 0.522, 0.75, 0.833, 0.76, 0.0, 0.978, 0.077, 0.278, 0.267, 0.182, 0.2, 0.667, 0.25, 0.333, 0.545, 0.049, 0.071, 0.571, 0.0, 0.067, 0.002, 0.356, 0.2, 0.418, 0.0, 0.08, 0.044, 0.6, 0.415, 0.375, 0.274, 0.631, 0.792, 0.833, 0.333, 0.8, 0.75, 1.0, 0.0, 0.4, 0.333, 0.333, 0.1, 0.333, 0.5, 0.625, 1.0, 1.0, 0.143, 0.163, 0.045, 0.1, 0.4, 0.083, 0.175, 0.0, 0.46, 0.618, 0.611, 0.5, 0.25, 0.25, 0.873]

In [150]:
a = []
for i in da:
    if i >=0.989 or i <= 0.010:
        a.append(i)
    else:
        a.append(0.5)

In [151]:
sum(True for i in a if i != 0.5)

15

In [152]:
a

[0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 1.0,
 0.0,
 0.5,
 0.5,
 0.996,
 0.5,
 0.5,
 0.5,
 0.5,
 0.0,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 1.0,
 0.5,
 0.5,
 0.0,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.0,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.0,
 0.5,
 0.002,
 0.5,
 0.5,
 0.5,
 0.0,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 1.0,
 0.0,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 1.0,
 1.0,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.0,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5]